<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Mirror.Server</AssemblyName>
    <RootNamespace>Mirror.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mirror.Application\Mirror.Application.csproj" />
    <ProjectReference Include="..\Mirror.Infrastructure\Mirror.Infrastructure.csproj" />
  </ItemGroup>

</Project>
